const Data = [
    {
      id: 1,
      category: "education",
      icon: "icon-graduation",
      year: "2021 - present",
      title: "Bachelors In Information Technology",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
      id: 2,
      category: "education",
      icon: "icon-graduation",
      year: "2019 - 2021",
      title: "FSC Pre-Engineering",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
      id: 3,
      category: "education",
      icon: "icon-graduation",
      year: "2017 - 2018",
      title: "Matriculation",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
      id: 4,
      category: "experience",
      icon: "icon-briefcase",
      year: "2022 - present",
      title: "Front-End Development",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
      id: 5,
      category: "experience",
      icon: "icon-briefcase",
      year: "2023 - present",
      title: "Back-End Developer",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
      id: 6,
      category: "experience",
      icon: "icon-briefcase",
      year: "2024 - present",
      title: "UI/UX Designer",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
  ];
export default Data
